export const STRINGS = {
  en: {
    hello:        'Hello',
    welcomeBack:  'Welcome Back 👋',
    signUpTitle:  'Create Account 🎉',
    name:         'Name',
    email:        'Email',
    password:     'Password',
    signIn:       'Sign In',
    signUp:       'Sign Up',
    haveAccount:  'Already have an account?',
    noAccount:    "Don't have an account?",
    searchHint:   'Search ice cream...',
    ourMenu:      'Our Menu',
    offerText:    'On your first order',
    offerBtn:     'Order Now',
    loading:      'Loading...',
    googleSignIn: 'Sign In with Google',
    chooseLanguage: 'Choose Language',
    langHint:     'You can change this in settings',
    // validation
    errName:    'Enter your name',
    errEmail:   'Enter a valid email',
    errPass:    'Password must be 6+ characters',
    errGeneric: 'Something went wrong',
  },
  gu: {
    hello:        'નમસ્તે',
    welcomeBack:  'પાછા આવ્યા 👋',
    signUpTitle:  'નોંધણી કરો 🎉',
    name:         'નામ',
    email:        'ઇમેઇલ',
    password:     'પાસવર્ડ',
    signIn:       'સાઇન ઇન',
    signUp:       'નોંધણી',
    haveAccount:  'પહેલેથી account છે?',
    noAccount:    'Account નથી?',
    searchHint:   'આઈસ્ક્રીમ શોધો...',
    ourMenu:      'અમારું મેનૂ',
    offerText:    'પ્રથમ ઓર્ડર પર',
    offerBtn:     'ઓર્ડર કરો',
    loading:      'લોડ થઈ રહ્યું છે...',
    googleSignIn: 'Google થી Sign In કરો',
    chooseLanguage: 'ભાષા પસંદ કરો',
    langHint:     'Settings માં ફેરવી શકાય',
    // validation
    errName:    'નામ દાખલ કરો',
    errEmail:   'માન્ય ઇમેઇલ દાખલ કરો',
    errPass:    'પાસવર્ડ ૬+ અક્ષર જોઈએ',
    errGeneric: 'કંઈક ખોટું થયું',
  },
};